// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Token struct {
	UserID pgtype.UUID
	Token  []byte
}

type User struct {
	ID        pgtype.UUID
	FirstName string
	LastName  string
	Email     string
	Password  []byte
}
